"""Bilingual and common-name aliases for imported DTU study programmes."""

PROGRAM_ALIASES: dict[str, tuple[str, ...]] = {
    # Bachelor programmes
    "anvendt-matematik": (
        "applied mathematics",
        "applied math",
        "matematik og teknologi",
        "mathematics and technology",
    ),
    "baeredygtigt-energidesign": ("sustainable energy design",),
    "bioteknologi": ("biotechnology", "biotech", "bachelor biotechnology", "bsc biotechnology"),
    "byggeteknologi": ("building technology", "civil engineering", "bachelor civil engineering"),
    "bygningsdesign": ("building design", "architectural engineering", "bachelor architectural engineering"),
    "computer-engineering": ("computerteknologi", "computer engineering bachelor"),
    "cyberteknologi": ("cyber technology", "cyber engineering"),
    "data-science-og-management": ("data science and management",),
    "design-og-innovation": ("design and innovation", "bachelor design and innovation"),
    "elektroteknologi": ("electrical engineering", "bachelor electrical engineering", "electrical technology"),
    "fysik-og-ingenioervidenskab": ("physics and engineering", "engineering science and physics"),
    "general-engineering": ("generel ingeniørvidenskab",),
    "geofysik-og-rumteknologi": (
        "earth and space physics and engineering",
        "bachelor earth and space physics and engineering",
    ),
    "kemi-og-teknologi": ("chemistry and technology", "chemistry and engineering"),
    "kunstig-intelligens-og-data": ("artificial intelligence and data", "ai and data"),
    "medicin-og-teknologi": ("medicine and technology", "medicine and engineering"),
    "mekanisk-design-og-teknologi": ("mechanical design and technology",),
    "miljoeteknologi": ("environmental engineering", "bachelor environmental engineering", "environmental technology"),
    "softwareteknologi": ("software technology", "software engineering bachelor"),
    "teknisk-biomedicin": ("technical biomedicine", "biomedical engineering", "bachelor biomedical engineering"),
    "teknologi-digital": ("digital technology", "technology digital", "digital engineering"),

    # MSc programmes
    "applied-chemistry": ("anvendt kemi",),
    "architectural-engineering": ("bygningsdesign kandidat", "arkitektonisk ingeniørvidenskab"),
    "autonomous-systems": ("autonome systemer",),
    "bioinformatics": ("bioinformatik",),
    "biomaterial-engineering-for-medicine": (
        "biomaterialeteknologi til medicin",
        "biomaterialer til medicin",
    ),
    "biomedical-engineering": ("biomedicinsk teknologi", "biomedicinsk ingeniørvidenskab"),
    "biotechnology": ("bioteknologi", "biotek kandidat"),
    "business-analytics": ("forretningsanalyse",),
    "chemical-and-biochemical-engineering": ("kemisk og biokemisk teknologi",),
    "civil-engineering": ("byggeteknologi kandidat", "byggeri kandidat"),
    "communication-technologies-and-system-design": (
        "kommunikationsteknologier og systemdesign",
        "kommunikationsteknologi og systemdesign",
    ),
    "computer-science-and-engineering": (
        "datalogi",
        "computer science",
        "computer science kandidat",
        "cse",
    ),
    "design-and-innovation": ("design og innovation",),
    "earth-and-space-physics-and-engineering": ("geofysik og rumteknologi",),
    "electrical-engineering": ("elektroteknologi", "elektroteknik"),
    "engineering-acoustics": ("teknisk akustik", "ingeniørakustik"),
    "engineering-light": ("lysteknologi", "lysdesign og teknologi"),
    "engineering-physics": ("teknisk fysik", "ingeniørfysik"),
    "environmental-engineering": ("miljøteknologi", "miljøteknik"),
    "food-technology": ("fødevareteknologi",),
    "human-centered-artificial-intelligence": (
        "menneskecentreret kunstig intelligens",
        "human centered ai",
        "hcai",
    ),
    "industrial-engineering-and-management": (
        "industriel økonomi og teknologiledelse",
        "industriel ingeniørvidenskab og ledelse",
    ),
    "materials-and-manufacturing-engineering": (
        "materiale og fremstillingsteknologi",
        "materialer og produktion",
    ),
    "mathematical-modelling-and-computation": (
        "matematisk modellering og beregning",
        "matematisk modellering og computation",
        "mmc",
    ),
    "mechanical-engineering": ("maskinteknik", "mekanisk teknologi"),
    "ocean-engineering": ("havteknik", "maritim ingeniørvidenskab"),
    "pharmaceutical-design-and-engineering": ("lægemiddeldesign og teknologi",),
    "sustainable-energy-systems": ("bæredygtige energisystemer",),
    "sustainable-energy-technologies": ("bæredygtige energiteknologier",),
    "sustainable-fisheries-and-aquaculture": ("bæredygtigt fiskeri og akvakultur",),
    "technology-entrepreneurship": ("teknologientreprenørskab", "teknologi entreprenørskab"),
    "wind-energy": ("vindenergi",),
}
